stages:
  preprocessing:
    cmd: python prepare_dataset.py
    deps:
    - data/iris.csv
    - prepare_dataset.py
    outs:
    - data/test/iris_test.csv
    - data/train/iris_train.csv
  kmeans_train:
    cmd: python k-means/k-means.py
    deps:
    - data/test/iris_test.csv
    - data/train/iris_train.csv
    - k-means/k-means.py
    outs:
    - k-means/predict.txt
  eval:
    cmd: python evaluate.py
    deps:
    - data/test/iris_test.csv
    - evaluate.py
    - k-means/k-means.py
    - k-means/predict.txt
    metrics:
    - metrics.txt
